version: '3.8'

services:
  redis:
    image: redis
    restart: always
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  worker:
    restart: always
    build:
      context: ./app
    env_file:
      - ./.env.prod
    command: [ "celery", "-A", "website", "worker", "-l", "info" ]
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_db

volumes:
  postgres_data:

